### ISSUE TITLE
Make code easier for change

### ISSUE THREAD

**Issue by pepol** [Compotes/NemT#5]
Currently, there are a lot of values hardcoded in the NemT. This is not a good thing, since changing one value can result in 5 or more changes needed in the source, that can easily be overlooked.

The task here is to put constant, internal values into constants and other values that may be tweakable into parameters of either the constructor of the class, or certain methods.

@magic-sudo could you take a look at this?

**Comment by gkaretka** [comment]
ok

**Comment by pepol** [comment]
Fixed by: #6 
Thanks @magic-sudo, closing this.
